"""
Adaptive-exercise service.

The whole feature in one place, as two explicit steps:

    1. assess_level(metrics)      -> which phonemes are weak + an overall level
    2. generate_exercise(...)     -> one practice sentence targeting those
                                     weak phonemes, drawn from the tagged
                                     exercise bank (retrieval) or, if the
                                     bank has no good match, generated by an
                                     LLM and verified with the SAME G2P
                                     pipeline before it's accepted.

"metrics" is a plain per-phoneme score map: {phoneme: score} with score in
[0, 1], where 1.0 means the user pronounces that sound reliably and 0.0
means they consistently miss it. That's exactly what the app stores per
profile (mastery = alpha / (alpha + beta)), so this service works both
statelessly (pass metrics in) and against a saved profile (load its stored
metrics).

`g2p_convert` / `ipa_to_tokens` are passed in by the caller (app.py) rather
than imported, so this module never imports app.py (no circular import) and
verification always uses the exact same G2P path the user is later scored
against.
"""

from __future__ import annotations

from typing import Callable, Dict, List, Optional

import content
import db

# A sound at or below this score is treated as a weak spot worth drilling.
WEAK_THRESHOLD = 0.6
# A sound at or above this score (well practiced) shouldn't dominate new
# exercises -- we steer away from padding sentences with it.
STRONG_THRESHOLD = 0.8
# How many weak sounds a single exercise tries to target at once. Kept small
# (2) so each exercise stays focused and can pack in many reps of just those
# sounds rather than spreading thin across several.
MAX_TARGETS = 2


def assess_level(metrics: Dict[str, float]) -> Dict:
    """Step 1: turn raw per-phoneme scores into a level assessment.

    Returns the weakest phonemes (to target), the strong ones (to avoid
    overloading), and a coarse overall level label derived from the mean
    score -- a simple, explainable summary, not a validated CEFR band.
    """
    clean = {p: float(s) for p, s in (metrics or {}).items() if p}

    weak = sorted((p for p, s in clean.items() if s <= WEAK_THRESHOLD), key=lambda p: clean[p])
    strong = {p for p, s in clean.items() if s >= STRONG_THRESHOLD}

    if not clean:
        overall = "unknown"
        mean_score = None
    else:
        mean_score = sum(clean.values()) / len(clean)
        if mean_score < 0.5:
            overall = "beginner"
        elif mean_score < 0.75:
            overall = "intermediate"
        else:
            overall = "advanced"

    return {
        "overall_level": overall,
        "mean_score": round(mean_score, 3) if mean_score is not None else None,
        "weak_phonemes": weak[:MAX_TARGETS],
        "all_weak_phonemes": weak,
        "strong_phonemes": sorted(strong),
        "tracked_phoneme_count": len(clean),
    }


def generate_exercise(
    metrics: Dict[str, float],
    g2p_convert: Callable[[str], str],
    ipa_to_tokens: Callable[[str], List[str]],
    recently_served_ids: Optional[set] = None,
) -> Dict:
    """Steps 1 + 2: assess the metrics, then produce one suitable exercise.

    Selection order:
      * No usable metrics yet -> a broad diagnostic sentence (the
        widest-coverage sentence in the bank), so a brand-new user still
        gets something sensible.
      * Weak sounds identified -> retrieve the best-matching bank sentence.
      * Bank has no sentence that covers enough of the target sounds ->
        fall back to LLM generation, verified against the G2P pipeline, and
        cache the accepted result into the bank for next time.

    Returns a self-contained exercise dict (sentence + IPA + which sounds it
    targets + how it was sourced). Never returns an unverified sentence.
    """
    recently_served_ids = recently_served_ids or set()
    assessment = assess_level(metrics)
    target_phonemes = assessment["weak_phonemes"]
    strong_phonemes = set(assessment["strong_phonemes"])

    source_mode = "targeted"
    chosen: Optional[Dict] = None

    if not target_phonemes:
        source_mode = "diagnostic"
        chosen = content.pick_diagnostic_sentence(db.get_all_sentences(), recently_served_ids)
    else:
        candidates = db.get_sentences_covering_any(target_phonemes)
        best = content.pick_next_sentence(candidates, target_phonemes, strong_phonemes, recently_served_ids)

        required_overlap = (len(target_phonemes) + 1) // 2  # cover at least half the targets
        best_overlap = 0 if best is None else sum(1 for p in target_phonemes if p in best["phoneme_counts"])

        if best_overlap < required_overlap:
            generated = content.generate_and_verify_exercise(
                target_phonemes, strong_phonemes, content.TARGET_WORD_COUNT, g2p_convert, ipa_to_tokens
            )
            if generated is not None:
                new_id = db.insert_sentence(
                    text=generated["text"],
                    reference_ipa=generated["reference_ipa"],
                    word_count=generated["word_count"],
                    level_proxy=generated["level_proxy"],
                    phoneme_counts=generated["phoneme_counts"],
                    source="llm_generated",
                )
                if new_id is not None:
                    generated["id"] = new_id
                    best = generated
                    source_mode = "generated"

        if best is None:
            source_mode = "diagnostic"
            chosen = content.pick_diagnostic_sentence(db.get_all_sentences(), recently_served_ids)
        else:
            chosen = best

    if chosen is None:
        return {
            "assessment": assessment,
            "exercise": None,
            "error": "No exercises available. Run scripts/build_exercise_bank.py to populate the bank.",
        }

    return {
        "assessment": assessment,
        "source_mode": source_mode,
        "target_phonemes": target_phonemes,
        "exercise": {
            "sentence_id": chosen["id"],
            "text": chosen["text"],
            "reference_ipa": chosen["reference_ipa"],
        },
    }


def metrics_for_user(user_name: str) -> Dict[str, float]:
    """Load a saved profile's stored per-phoneme metrics as a plain score
    map (mastery = alpha / (alpha + beta)). Empty dict if the profile has no
    history yet or doesn't exist."""
    user_row = db.get_user_by_name(user_name)
    if user_row is None:
        return {}
    metrics = {}
    for row in db.get_all_phoneme_states(user_row["id"]):
        total = row["alpha"] + row["beta"]
        metrics[row["phoneme"]] = (row["alpha"] / total) if total else 0.5
    return metrics
